### ISSUE TITLE
bug:   7.22.0 next build error TRPCClientError: Dynamic server usage

### ISSUE THREAD

**Issue by luz33c** [t3-oss/create-t3-app#1599]
### Provide environment information

 "ct3aMetadata": {
    "initVersion": "7.22.0"
  },

### Describe the bug

<img width="755" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/62172559/d8fcba5a-948e-45a2-9c26-33af5892228e">

### Reproduction repo
.

### To reproduce

when：
- install： `pnpm create t3-app@latest`
- use nextjs  appdir option 
- build：` pnpm build`

**Comment by BeauSLM** [comment]
https://github.com/t3-oss/create-t3-app/pull/1567#issuecomment-1748418796

this fix got rid of the issue for me - should it ship with by default?

**Comment by dBianchii** [comment]
Same happening here!

**Comment by c-ehrlich** [comment]
Thanks for the issue. Can reproduce. Weirdly enough this issue exists for the `hello` query but not for the query that gets all posts. `force-dynamic` works as a band-aid, but feels less than optimal. Will research further.

**Comment by dBianchii** [comment]
I was trying to investigate this and I'm reading [this page](https://nextjs.org/docs/messages/dynamic-server-error) but I'm not understanding anything about it. If someone understands this in some way and would like to explain in more layman's terms, I would appreciate it.
I believe the error is coming from here: https://github.com/t3-oss/create-t3-app/blob/d1a895533d204935a5eb7d11ff56a9a4d369bfda/cli/template/extras/src/trpc/server.ts#L23

**Comment by markomitranic** [comment]
@c-ehrlich From my limited testing i can see that using `TRPCReactProvider` on a layout level produces a `DYNAMIC_SERVER_USAGE` error as it is unable to produce the entire page statically due to a use of headers.

When I instead move the provider elsewhere, and only have it wrap the actual components that wish to access `~/trpc/react`, the error disappears as it is now limiting the dynamicness only to a certain component. It ain't pretty, as it requires us to wrap components. In this scenario I didn't have to resort to forcing dynamic, it seems to be able to decide on its own.

**Now, not saying this is a solution but leaving this here hoping it is helpful to someone, until we find a better one...**

All the while, `~/trpc/server` works just fine without a need of a provider, and produces no errors. :) 

--

P.S. Not sure how wrapping each element in `TRPCReactProvider` affects memory and that stuff, so there is also a secondary option instead of having to throw a kazzilion `TRPCReactProvider` around your components. We did this pattern very often when it comes to shared state, contexts and providers - conditionally wrap the layout ONLY when is client, otherwise print children as-is.

```tsx
    <html lang="en">
      <body>
        <main>
          <WrapOnlyClient
            wrapper={
              <TRPCReactProvider headers={headers()}>
                {children}
              </TRPCReactProvider>
            }
          >
            {children}
          </WrapOnlyClient>
        </main>
      </body>
    </html>
```

In this scenario, the page will SSR as-is, and will have no provider during SSR, but will actually have a provider in the client, allowing the client components to do their work. The major issue with this is that you then also must ensure that you don't mount (only) the offending client components during SSR, effectively making them client-only or mounted-only.

```tsx
some/page.tsx
<OnlyClient><ContainsTrpcCalls /></OnlyClient>
```

**Comment by tartom7997** [comment]
The following wrapper does not work in my repo...
It seems that writing "force-dynamic" in layout.tsx deletes the error but in docker composing the error occurs. 

>// layout.tsx
    <html lang="en">
      <body>
        <main>
          <WrapOnlyClient
            wrapper={
              <TRPCReactProvider headers={headers()}>
                {children}
              </TRPCReactProvider>
            }
          >
            {children}
          </WrapOnlyClient>
        </main>
      </body>
    </html>

**Comment by jonbergan** [comment]
Experienced this issue today also when trying to build a new app with the latest T3. `'force-dynamic'` seemed to resolve the issue for me but certainly doesn't feel ideal. Keen to see the proper solution for this come through.

**Comment by TCGAUD** [comment]
Same issue here

**Comment by juliusmarminge** [comment]
Idk what @KATT thinks but i'd say this issue should be moved to trpc as it's something we should look into from there on how to properly recommend using trpc/react-query and forwarding headers correctly?

**Comment by ImBIOS** [comment]
I only found these in the example bundled with t3, I never found it in any of my other projects.

I experimented by splitting all `await` into its independent components and then wrapping it with `Suspense`, the error went into the abyss in no time.

I suspect, it's Next.js trying to make all RSC static by default and only parts of its page are interactable which is dynamic. Whenever Next.js detects `headers()` or `cookies()` passed to the component, it normally catches it and makes the page dynamic, this error means, the error isn't watched properly for some reason.

**Comment by simonri** [comment]
> I only found these in the example bundled with t3, I never found it in any of my other projects.
> 
> I experimented by splitting all `await` into its independent components and then wrapping it with `Suspense`, the error went into the abyss in no time.
> 
> I suspect, it's Next.js trying to make all RSC static by default and only parts of its page are interactable which is dynamic. Whenever Next.js detects `headers()` or `cookies()` passed to the component, it normally catches it and makes the page dynamic, this error means, the error isn't watched properly for some reason.

Wrapping the components in Suspense worked as a temporary solution for me as well.

**Comment by benfavre** [comment]
Switching from node 18 to 20 fixes this for me

**Comment by jonbergan** [comment]
That seems random since it doesn’t appear to be a node issue rather Next throwing a valid error..?

**Comment by simonri** [comment]
> Switching from node 18 to 20 fixes this for me

Doesn't work for me

**Comment by LudoLogical** [comment]
+1 on this bug report, I'm running node v20.9.0
The issue is also present when deploying to Vercel

**Comment by liuhe2020** [comment]
Same issue for me, and the funny thing is it doesn't happen to all pages. Some pages are completely fine and the setup is exactly the same, just calling for different data from the db.

**Comment by henokyehulu** [comment]
Encounterd this issue today. Any solutions devs?

**Comment by danieljpgo** [comment]
This also happens on my side, it is impossible to on static pages, it is limiting everything to SSR.

**Comment by Andrii-Antoniuk** [comment]
Same bug today for me 
`"initVersion": "7.23.2"`

**Comment by luthfimasruri** [comment]
Today, I encountered this issue. Any updates on the fix?

<img width="901" alt="Screenshot 2023-11-19 at 14 40 26" src="https://github.com/t3-oss/create-t3-app/assets/6185447/7bee9117-f8ee-4b07-93b5-6fb200283240">

**Comment by Lucasvo1** [comment]
Having the same issue.

**Comment by keelangibb** [comment]
So, this is not causing a build issue anymore, but it is forcing all routes to become force-dynamic because of the use of headers and cookies I think. Even without using trpc on a barebones page.tsx. Anyone know of a workaround? "initVersion": "7.24.0"

**Comment by LudoLogical** [comment]
@keelangibb might be worth opening a new issue over and referencing this one in that one? Technically, this issue is resolved and should be closed, but obviously the behavior you're experiencing is problematic.

**Comment by rydonahue1** [comment]
> e? Technically, this issue is resolved and should be closed, but obviously the behavior you're experiencing is problematic.

Just did a pull of the repo today and was still getting the bug mentioned by OP, in just the base T3 app. I have been reading a ton of these threads and managed to find a few work arounds, but they all seem like a rather quick fix Band-Aid than an actual solution.

Is there any recommendation by the T3 team on how to bypass this error or is it safe to ignore because the app still technically builds?

**Comment by Lukem121** [comment]
Also getting Dynamic server usage: Page couldn't be rendered statically because it used `headers`.

**Comment by bored-yuns** [comment]
So how exactly do you fix this?

**Comment by andrewmartin** [comment]
Curious if this is something we can fix, do we need `headers()` in the TRPC context?

**Comment by gorkamolero** [comment]
This seems to be a solution:

https://github.com/orgs/vercel/discussions/4696#discussioncomment-7494345

```
import { api } from '@/trpc/server';
import { unstable_noStore as noStore } from 'next/cache';

async function getIdeas() {
  noStore();
  const ideas = await api.ideas.getAll.query();
  return ideas;
}
```
